# Generated by Django 5.0.6 on 2024-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
