# Generated by Django 5.0.6 on 2024-05-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_category_options_alter_todo_options_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_doned_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
