# Generated by Django 5.0.6 on 2024-05-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_user_doned_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_doned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
