# Generated by Django 5.0.6 on 2024-05-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_user_doned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_doned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
