# Generated by Django 5.0.6 on 2024-05-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_done_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_doned',
        ),
    ]
