# Generated by Django 5.0.6 on 2024-05-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='value',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='value',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='name',
            new_name='title',
        ),
    ]
