# Generated by Django 5.0.6 on 2024-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bankname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='iban',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
