# Generated by Django 5.0.6 on 2024-05-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_bankname_alter_member_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='canceled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
